Testwork
Darya-Nazir/event_testwork_8 pull request #1
Opened 2024-01-14 18:05 UTC by Darya-Nazir

2024-01-14 20:25 UTC, eugenenazirov requested changes
Пока что работу не принимаю. 

1. Пожалуй, самое главное упущение, которое ломает всю работу сайта: Как пользователь я не получаю НИ ОДНОГО сообщения о неправильном заполнении формы, т.к. все сообщения летят в консоль. По ТЗ ты должна выводить их в алерт. Мы уже обсуждали что не стоит выводить их по одному, потому что с такого сайта легче сбежать, чем прокликать все эти алерты. Поэтому необходимо выводить ВСЕ сообщение об ошибках в одном алерте. Этого будет достаточно для работы на 3.

2. Шрифты для инпутов отображаются некорректно, это нарушает требование соответствия макету. Пароли при вводе не должны быть видны, это базовое требование безопасности (если только по тз и макету у тебя нет кнопки "подсмотреть пароль").
Эти исправления достаточны для работы на 4.

3. Также нет никакой возможности вернуться на страницу регистрации со страницы логина. Да, в тз нет ни слова про это, но это как раз важный кейс, когда ты должна "додумать" тз, с точки зрения удобства пользователя. Просто представь что будет, если я захочу зарегистрировать новую учетную запись, а не входить со старой :)
Этого хватит для работы на 5.

4. Круто, что ты поработала с массивом boolean для обработки результатов валидации. Не круто, что ты работаешь с этим массивом по-сути как с глобальной переменной (да, она по факту не глобальная, так как код завернут в функцию-обработчик, но семантика именно такая) и меняешь её состояние из разных участков кода. Это очень плохая практика, так как она усложняет отладку и даёт место для тонны потенциальных багов (представь что тебе нужно будет еще в 3-4 функциях поменять состояние этого массива, а они еще и раскиданы у тебя по разным модулям/файлам. Ты просто заколебёшься отлаживать, что ж там у тебя происходит с этим массивом и в какой момент. Это во-первых.
Во-вторых - непонятно что это за `booleanArray` такой и зачем он нужен для всего скрипта. Это конечно можно решить неймингом, но дело здесь даже не в нем.
Если DOM-элементы, которые ты кладёшь в такие же глобальные переменные имеют ценность сами по себе, и не вызывают вопросов "для чего они здесь", то booleanArray такой неоспоримой ценности не имеет. Такой массив - неотъемлемая часть логики валидации. Без неё он просто не нужен. Поэтому стоит задуматься над тем, чтобы определять его на уровне функции-валидатора.
Поэтому предлагаю пересмотреть логику работы функций-валидаторов, сделать их чистыми (для начала), и исключить разделяемый ресурс из разных функций (в данном случае массив `booleanArray`), чтобы управление им происходило только на одном уровне.
Это будет работа на 5+

5. Также много мелких замечаний по стилю кода: отступам, пустым строкам, неймингу. Это тоже конечно нужно поправить, но на работу не влияет.

2024-01-14 20:25 UTC, eugenenazirov commented on script.js
> +            booleanArray.push(false);
Функция называется `isValidFields`, но её результатом не является булевый ответ. Не надо так.

2024-01-14 20:25 UTC, eugenenazirov commented on script.js
> +            booleanArray.push(true);
Вместо булевого результата ты меняешь состояние массива в глобальной переменной. Это так себе практика, и здесь она точно не оправдана. Подробнее см. в общем ревью-комменте.

2024-01-14 20:29 UTC, eugenenazirov commented on script.js
> +        if (booleanArray.includes(false)) {
Ты правильно поняла идею про проверку на хотя бы одно falsy значение, но есть более удачные реализации такой идеи. Подробнее смотри про методы массивов `every()` и `some()`. https://doka.guide/js/array-every/

2024-01-18 13:27 UTC, eugenenazirov requested changes
Форма всё еще работает некорректно. Регистрация проходит, даже если не отмечен чекбокс, а он обязателен. Принять работу всё еще не могу в силу невыполненных функциональных требований ТЗ.

Остальные ошибки валидации выводятся корректно, не спамят алертами, а выводятся в одном. Работа с глобальной переменной убрана, стилистика кода исправлена. Эти изменения принимаются.

Работа с валидацией по-прежнему печальная. Проблема формирования общего сообщения об ошибках в алерт была решена "в лоб" и привела к очень сильному дублированию кода. Представь, что заказчик изменил требования к валидации и теперь необходимая длина пароля 10 символов. И вот, достаточно забыть поменять цифру в одном из мест, как все моментально ломается. В booleanArray добавляется значение `false`, а пользователю летит пустой алерт, потому что вторая проверка не выполняется корректно. 
Сейчас у тебя необходимые проверки написаны дважды: в отдельных функциях с соответствующими названиями (где они и должны быть) и в функции showPopup (где их быть не должно).

Я напоминаю о своей рекомендации для начала сделать функции валидации "чистыми", а уже затем думать как их выполнить все вместе по очереди и забрать результаты.

Необходимость собрать все ошибки в одну строку не должна приводить тебя к таким костылям. Есть как минимум два подхода как решить эту задачу без дублирования кода, изящно собирая и обрабатывая ошибки.

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +    }
Зачем разбивать? Ты уже создала все нужные функции с проверками. А снова пишешь те же самые проверки, только вручную, как будто никаких функций и не было. Зачем тогда нужно было их писать?)) Это же колоссальное дублирование кода. Разве тебе не впадлу было писать проверки по второму кругу здесь? Да и причем тут проверки, когда функция называется showPopup?

Нужно по-максимуму переиспользовать уже написанный код, но для этого твой код должен быть удобен для переиспользования. Еще на первом ревью я посоветовал тебе сделать функции, которые делают сами проверки чистыми. Ты или забыла, или не поняла смысл, но из-за этого твои функции так и остались грязными. Хоть это и не ошибка, но из-за этого ты и не можешь их нормально переиспользовать, и тебе приходится городить костыли как здесь. Самую грубую ошибку с глобальными переменными ты пофиксила успешно.

Общая строка на все ошибки может быть составлена из отдельных строк для каждой ошибки.
![image](https://github.com/Darya-Nazir/event_testwork_8/assets/86873558/1b4e9f08-d37d-4bb6-aaec-88e58d924f02)

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +    }
Конкретная хитрожопость видна здесь, и в реальных SPA так делать нельзя. Но за изобретательность и поиск "короткого пути" - лайк.

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +    function goLoginForm() {
Прикольно, но лучше назвать `sendLoginForm` или `performLogin`, да `doLogin` на худой конец.

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +    function handlerForLogin() {
Лучше `loginHandler`. Меньше слов, больше дела)

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +    // theSamePasswordInput.onblur = isPasswordsTheSame;
Так нужно это в итоге или нет?

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +        }
В таких случаях сам Бог велел использовать тернарный оператор.

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +        if (passwordValue.length < 8) {
Цифра 8 в данном случае является "магическим числом", а это дурной тон в программировании.

2024-01-18 13:27 UTC, eugenenazirov commented on scripts/script.js
> +        }
Тернарный оператор - приди!

2024-01-21 14:56 UTC, eugenenazirov approved these changes
Отличная работа! Ты многому научилась и много косяков исправила. Отдельно хочу отметить использование метода `.filter()` и использование локальных переменных вместо глобальных (например, для запрещенных символов). Работа на 5+.

Теперь чувствую, что не зря сидел с тобой несколько часов над этим. Код теперь выглядит по-настоящему круто, тянет на уровень middle.

Поправь пару совсем мелких моментов. Они не влияют на оценку, поэтому запрашивать изменения не буду. Долгожданный аппрув твой.

2024-01-21 14:56 UTC, eugenenazirov commented on scripts/script.js
>      function isAgree(evt) {
Удали неиспользуемый параметр.

2024-01-21 14:56 UTC, eugenenazirov commented on scripts/script.js
> +        const invalidSymbols = [".", ","]
Отличное решение! Этим символам здесь самое место.

2024-01-21 14:56 UTC, eugenenazirov commented on scripts/script.js
> +        return inputsArray.filter(input => input.value.trim() === '');
Шикааарно! Использовать .filter() - самое то для таких задач.

2024-01-21 14:56 UTC, eugenenazirov commented on scripts/script.js
> +        return true;
Зачем `showPopup` возвращать `true`? Зачем вообще этой функции что-то возвращать? Где ты будешь использовать возвращенный результат? Есть ли здесь сценарий при котором функция будет возвращать что-то отличное от `true`?
Похоже, ты немного перестаралась с возвратами из функций :D

2024-01-21 14:56 UTC, eugenenazirov commented on scripts/script.js
> +        performLogin();
Лучше тогда назвать просто `login()`, чтобы было в едином стиле: функции `signUp()` и `login()` отвечают за выполнение целевого действия по клику на кнопку, на которой висит хендлер. Так сразу понятнее.

2024-01-21 16:13 UTC, Darya-Nazir commented on scripts/script.js
> +        return true;
нуу я для кодстайла решила сделать ее чистой))

2024-01-21 16:21 UTC, merged