New features
Darya-Nazir/event_testwork_8 pull request #2
Opened 2024-06-18 12:12 UTC by Darya-Nazir

2024-06-18 17:10 UTC, eugenenazirov requested changes
Неплохо. Код стал на порядок сложнее, но при этом читабельнее по сравнению с первой итерацией работы над этим сайтом. Это действительно похвально.

Общие замечания по работе сайта:
- При нажатии на Sign In (процедура логина) ничего не происходит.
- Валидация чекбокса при регистрации никак не показывается пользователю, то есть при нажатии Sign Up с пустым чекбоксом просто ничего не происходит, это не гуд. Надо хотя бы дизейблить кнопку, ну или показывать какой-нибудь паскудный alert, чтобы было понятно куда тыкнуть чтобы все поправить.
- Если сайт на английском языке, было бы неплохо, чтобы сообщения об ошибках валидации тоже были англоязычные)

2024-06-18 17:10 UTC, eugenenazirov commented on scripts/script.js
> +        createArray(client);
createArray не должен вызываться в createObject. Можно сделать что-то вроде saveUser, где вызывать createObject, который будет возвращать объект юзера, а дальше отправлять этот объект в createArray.

2024-06-18 17:10 UTC, eugenenazirov commented on scripts/script.js
> +        let client = {}
В силу специфичных айтишных терминов вокруг клиент-серверного взаимодействия, в коде не принято сущность "клиент" (в смысле покупатель, получатель услуг) называть как Client, вместо этого лучше использовать Customer или User, чтобы не было путаницы. Ну и вообще в английском наше слово клиент переводится обычно как Customer (потребитель).

2024-06-18 17:10 UTC, eugenenazirov commented on scripts/script.js
> +        // alert((emptyFieldsArray.length > 0) ? 'Необходимо заполнить все поля' : `Добро пожаловать, ${username.value}!`);
Видимо не хватает страницы личного кабинета, потому что сейчас ничего не происходит.

2024-06-18 17:10 UTC, eugenenazirov commented on scripts/script.js
> +        checkEmptyInputs(inputsArray);
Кажется areInputsFill и checkEmptyInputs должны делать одно и то же))

2024-06-19 08:36 UTC, eugenenazirov requested changes
Пофикси лишние вызовы функций. Всегда помни что ты не вызываешь например `.trim()` или `getElementByID()` дважды. А ведь это точно такие же функции, только написанные не тобой))

2024-06-19 08:36 UTC, eugenenazirov commented on scripts/script.js
> +    function welcomeToUser(usernameValue) {
Нейминг не самый удачный.
_"Добро пожаловать в пользователя"?_

2024-06-19 08:36 UTC, eugenenazirov commented on scripts/script.js
> +    function removeUnneededToAccView() {
Nit: тогда уж _unneeded for_.

2024-06-19 08:36 UTC, eugenenazirov commented on scripts/script.js
> +    }
👍🏿

2024-06-19 08:36 UTC, eugenenazirov commented on scripts/script.js
> +    function isDoubleCustomer() {
Nit: лучше тогда уж _isCustomerDuplicated_.

2024-06-19 08:36 UTC, eugenenazirov commented on scripts/script.js
> +                createObject(fullName, username, email, password);
Зачем здесь этот вызов?

2024-06-19 09:32 UTC, Darya-Nazir commented on scripts/script.js
> +// Ошибки нахождения в LS
Это Localastorage

2024-06-19 12:19 UTC, Darya-Nazir commented on scripts/script.js
> +                createObject(fullName, username, email, password);
Вызов проверяет, есть ли такой пользователь. Если нет, то выполняется код внутри, и сохраняется новый пользователь.

2024-06-19 12:35 UTC, eugenenazirov commented on scripts/script.js
> +                createObject(fullName, username, email, password);
Твое объяснение относится к строке выше. А то на что я обратил внимание - просто лишний вызов в молоко :)

2024-06-19 19:04 UTC, eugenenazirov approved these changes
Даже при довольно странном задании: реализовать несколько страниц силами одного лишь JS-скрипта, у тебя получилось сделать это хорошо и красиво. Думаю, ничего лучше с этой контрольной уже нельзя сделать. Грац!

2024-06-19 19:04 UTC, eugenenazirov commented on scripts/script.js
> +// Ошибки нахождения в LocalStorage
👍🏿

2024-06-19 19:04 UTC, eugenenazirov commented on scripts/script.js
> +    function welcomeToPersonalAcc(usernameValue) {
Супер!

2024-06-20 06:32 UTC, merged